apiVersion: v1
kind: Service
metadata:
  name: {{ include "microbin.fullname" . }}
  labels:
    {{- include "microbin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "microbin.selectorLabels" . | nindent 4 }}
