apiVersion: v1
kind: Service
metadata:
  namespace: nodered
  name: nodered
spec:
  selector:
    app: nodered
  ports:
    - protocol: TCP      
      port: 1880
      targetPort: 1880     
  type: ClientIP